kind: ServiceAccount
apiVersion: v1
metadata:
  name: husseinashah
  namespace: sn-labs-husseinashah
  uid: f3f082ee-4c48-44dc-9037-1e993b42c1f9
  resourceVersion: '809977774'
  creationTimestamp: '2023-01-04T11:20:50Z'
secrets:
  - name: husseinashah-dockercfg-wpwqg
imagePullSecrets:
  - name: icr
  - name: dh
  - name: husseinashah-dockercfg-wpwqg
