kind: ServiceAccount
apiVersion: v1
metadata:
  name: pipeline
  namespace: sn-labs-husseinashah
  uid: 80a1120d-69bc-4c2b-9645-20fd5b5ea913
  resourceVersion: '809977808'
  creationTimestamp: '2023-01-04T11:20:52Z'
  ownerReferences:
    - apiVersion: operator.tekton.dev/v1alpha1
      kind: TektonConfig
      name: config
      uid: 631e9f3a-b851-4dcf-bd04-5fbdcafeaf03
      controller: true
      blockOwnerDeletion: true
  managedFields:
    - manager: openshift-controller-manager
      operation: Update
      apiVersion: v1
      time: '2023-01-04T11:20:52Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:imagePullSecrets': {}
        'f:secrets':
          .: {}
          'k:{"name":"pipeline-dockercfg-skhg8"}': {}
    - manager: openshift-pipelines-operator
      operation: Update
      apiVersion: v1
      time: '2023-01-04T11:20:52Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:metadata':
          'f:ownerReferences':
            .: {}
            'k:{"uid":"631e9f3a-b851-4dcf-bd04-5fbdcafeaf03"}': {}
secrets:
  - name: pipeline-dockercfg-skhg8
imagePullSecrets:
  - name: pipeline-dockercfg-skhg8
