apiVersion: triggers.tekton.dev/v1alpha1
kind: ClusterTriggerBinding
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: >
      {"apiVersion":"triggers.tekton.dev/v1alpha1","kind":"ClusterTriggerBinding","metadata":{"labels":{"operator.tekton.dev/operand-name":"openshift-pipelines-addons"},"name":"github-pullreq-review-comment","namespace":"openshift-pipelines","ownerReferences":[{"apiVersion":"operator.tekton.dev/v1alpha1","blockOwnerDeletion":true,"controller":true,"kind":"TektonInstallerSet","name":"addon-triggers-dp95q","uid":"3594e4ac-d376-4433-9fad-299b588addf0"}]},"spec":{"params":[{"name":"comment","value":"$(body.comment.body)"},{"name":"comment-user-login","value":"$(body.comment.user.login)"},{"name":"merge-commit-sha","value":"$(body.pull_request.merge_commit_sha)"}]}}
    manifestival: new
  resourceVersion: '773077316'
  name: github-pullreq-review-comment
  uid: 5e7b8538-1a6c-4cd0-b454-afae82e464f2
  creationTimestamp: '2022-11-30T16:12:37Z'
  generation: 1
  managedFields:
    - apiVersion: triggers.tekton.dev/v1alpha1
      fieldsType: FieldsV1
      fieldsV1:
        'f:metadata':
          'f:annotations':
            .: {}
            'f:kubectl.kubernetes.io/last-applied-configuration': {}
            'f:manifestival': {}
          'f:labels':
            .: {}
            'f:operator.tekton.dev/operand-name': {}
          'f:ownerReferences':
            .: {}
            'k:{"uid":"3594e4ac-d376-4433-9fad-299b588addf0"}': {}
        'f:spec':
          .: {}
          'f:params': {}
      manager: manifestival
      operation: Update
      time: '2022-11-30T16:12:37Z'
  ownerReferences:
    - apiVersion: operator.tekton.dev/v1alpha1
      blockOwnerDeletion: true
      controller: true
      kind: TektonInstallerSet
      name: addon-triggers-dp95q
      uid: 3594e4ac-d376-4433-9fad-299b588addf0
  labels:
    operator.tekton.dev/operand-name: openshift-pipelines-addons
spec:
  params:
    - name: comment
      value: $(body.comment.body)
    - name: comment-user-login
      value: $(body.comment.user.login)
    - name: merge-commit-sha
      value: $(body.pull_request.merge_commit_sha)
