kind: HorizontalPodAutoscaler
apiVersion: autoscaling/v2beta2
metadata:
  name: guestbook
  namespace: sn-labs-husseinashah
  uid: b0450848-7384-46a7-bfdf-3e0b27bb1235
  resourceVersion: '810351605'
  creationTimestamp: '2023-01-04T18:58:03Z'
  managedFields:
    - manager: kubectl-autoscale
      operation: Update
      apiVersion: autoscaling/v1
      time: '2023-01-04T18:58:03Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:spec':
          'f:maxReplicas': {}
          'f:minReplicas': {}
          'f:scaleTargetRef': {}
          'f:targetCPUUtilizationPercentage': {}
    - manager: kube-controller-manager
      operation: Update
      apiVersion: autoscaling/v2
      time: '2023-01-04T19:00:19Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:status':
          'f:conditions':
            .: {}
            'k:{"type":"AbleToScale"}':
              .: {}
              'f:lastTransitionTime': {}
              'f:message': {}
              'f:reason': {}
              'f:status': {}
              'f:type': {}
            'k:{"type":"ScalingActive"}':
              .: {}
              'f:lastTransitionTime': {}
              'f:message': {}
              'f:reason': {}
              'f:status': {}
              'f:type': {}
            'k:{"type":"ScalingLimited"}':
              .: {}
              'f:lastTransitionTime': {}
              'f:message': {}
              'f:reason': {}
              'f:status': {}
              'f:type': {}
          'f:currentMetrics': {}
          'f:currentReplicas': {}
          'f:desiredReplicas': {}
          'f:lastScaleTime': {}
      subresource: status
spec:
  scaleTargetRef:
    kind: Deployment
    name: guestbook
    apiVersion: apps/v1
  minReplicas: 1
  maxReplicas: 10
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 5
status:
  lastScaleTime: '2023-01-04T19:41:35Z'
  currentReplicas: 1
  desiredReplicas: 1
  currentMetrics:
    - type: Resource
      resource:
        name: cpu
        current:
          averageValue: '0'
          averageUtilization: 0
  conditions:
    - type: AbleToScale
      status: 'True'
      lastTransitionTime: '2023-01-04T18:58:18Z'
      reason: ReadyForNewScale
      message: recommended size matches current size
    - type: ScalingActive
      status: 'True'
      lastTransitionTime: '2023-01-04T19:13:37Z'
      reason: ValidMetricFound
      message: >-
        the HPA was able to successfully calculate a replica count from cpu
        resource utilization (percentage of request)
    - type: ScalingLimited
      status: 'True'
      lastTransitionTime: '2023-01-04T19:41:35Z'
      reason: TooFewReplicas
      message: the desired replica count is less than the minimum replica count
