apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-sne
spec:
  selector:
    matchLabels:
      run: hello-sne
  template:
    metadata:
      labels:
        run: hello-sne
    spec:
      containers:
      - name: hello-sne
        image: us.icr.io/sn-labs-husseinashah/hello-sne:1
        ports:
        - containerPort: 8080
        resources:
          limits:
            cpu: 2m
            memory: 30Mi
          requests:
            cpu: 1m
            memory: 10Mi  
        
      imagePullSecrets:
        - name: icr
