kind: BuildConfig
apiVersion: build.openshift.io/v1
metadata:
  annotations:
    app.openshift.io/vcs-ref: ''
    app.openshift.io/vcs-uri: >-
      https://github.com/husseinahmed-dev/Research-Project-1-Kubernetes-Hardening.git
    openshift.io/generated-by: OpenShiftWebConsole
  resourceVersion: '810396014'
  name: guestbook-v2
  uid: b89c7487-de84-415e-b195-8779aa693b78
  creationTimestamp: '2023-01-04T20:40:35Z'
  generation: 2
  managedFields:
    - manager: Go-http-client
      operation: Update
      apiVersion: build.openshift.io/v1
      time: '2023-01-04T20:40:35Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:status':
          'f:lastVersion': {}
    - manager: Mozilla
      operation: Update
      apiVersion: build.openshift.io/v1
      time: '2023-01-04T20:40:35Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:metadata':
          'f:annotations':
            .: {}
            'f:app.openshift.io/vcs-ref': {}
            'f:app.openshift.io/vcs-uri': {}
            'f:openshift.io/generated-by': {}
          'f:labels':
            .: {}
            'f:app': {}
            'f:app.kubernetes.io/component': {}
            'f:app.kubernetes.io/instance': {}
            'f:app.kubernetes.io/part-of': {}
        'f:spec':
          'f:output':
            'f:to': {}
          'f:runPolicy': {}
          'f:source':
            'f:contextDir': {}
            'f:git':
              .: {}
              'f:uri': {}
            'f:type': {}
          'f:strategy':
            'f:dockerStrategy':
              .: {}
              'f:dockerfilePath': {}
            'f:type': {}
          'f:triggers': {}
  namespace: sn-labs-husseinashah
  labels:
    app: guestbook-v2
    app.kubernetes.io/component: guestbook-v2
    app.kubernetes.io/instance: guestbook-v2
    app.kubernetes.io/part-of: research-project-1-kubernetes-hardening-git-app
spec:
  nodeSelector: null
  output:
    to:
      kind: ImageStreamTag
      name: 'guestbook-v2:latest'
  resources: {}
  successfulBuildsHistoryLimit: 5
  failedBuildsHistoryLimit: 5
  strategy:
    type: Docker
    dockerStrategy:
      dockerfilePath: Dockerfile
  postCommit: {}
  source:
    type: Git
    git:
      uri: >-
        https://github.com/husseinahmed-dev/Research-Project-1-Kubernetes-Hardening.git
    contextDir: /applications/4_APP (Guestbook)/v2/guestbook
  triggers:
    - type: Generic
      generic:
        secretReference:
          name: guestbook-v2-generic-webhook-secret
    - type: GitHub
      github:
        secretReference:
          name: guestbook-v2-github-webhook-secret
    - type: ConfigChange
  runPolicy: Serial
status:
  lastVersion: 1
