kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: tektonchains.operator.tekton.dev-v1alpha1-crdview
  uid: c8bba809-dc2b-4e70-9073-a76b33be6f9d
  resourceVersion: '757693744'
  creationTimestamp: '2022-11-16T15:25:20Z'
  labels:
    olm.opgroup.permissions/aggregate-to-22e514fea180dc6f-view: 'true'
    rbac.authorization.k8s.io/aggregate-to-view: 'true'
  ownerReferences:
    - apiVersion: apiextensions.k8s.io/v1
      kind: CustomResourceDefinition
      name: tektonchains.operator.tekton.dev
      uid: 07f9ac58-f66c-4f58-8dff-e34ae2045bdf
      controller: false
      blockOwnerDeletion: false
  managedFields:
    - manager: olm
      operation: Update
      apiVersion: rbac.authorization.k8s.io/v1
      time: '2022-11-16T15:25:20Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:metadata':
          'f:labels':
            .: {}
            'f:olm.opgroup.permissions/aggregate-to-22e514fea180dc6f-view': {}
            'f:rbac.authorization.k8s.io/aggregate-to-view': {}
          'f:ownerReferences':
            .: {}
            'k:{"uid":"07f9ac58-f66c-4f58-8dff-e34ae2045bdf"}': {}
        'f:rules': {}
rules:
  - verbs:
      - get
    apiGroups:
      - apiextensions.k8s.io
    resources:
      - customresourcedefinitions
    resourceNames:
      - tektonchains.operator.tekton.dev
