kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: cert-manager-controller-ingress-shim
  uid: 67d98692-ea37-4f90-bc5b-8683d550dd2c
  resourceVersion: '268137129'
  creationTimestamp: '2021-05-26T21:16:53Z'
  labels:
    app: cert-manager
    app.kubernetes.io/component: controller
    app.kubernetes.io/instance: cert-manager
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: cert-manager
    app.kubernetes.io/version: v1.7.1
    helm.sh/chart: cert-manager-v1.7.1
  annotations:
    meta.helm.sh/release-name: cert-manager
    meta.helm.sh/release-namespace: cert-manager
  managedFields:
    - manager: Go-http-client
      operation: Update
      apiVersion: rbac.authorization.k8s.io/v1
      time: '2021-11-22T23:20:43Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:metadata':
          'f:annotations':
            .: {}
            'f:meta.helm.sh/release-name': {}
            'f:meta.helm.sh/release-namespace': {}
          'f:labels':
            .: {}
            'f:app': {}
            'f:app.kubernetes.io/component': {}
            'f:app.kubernetes.io/instance': {}
            'f:app.kubernetes.io/managed-by': {}
            'f:app.kubernetes.io/name': {}
            'f:app.kubernetes.io/version': {}
            'f:helm.sh/chart': {}
        'f:rules': {}
rules:
  - verbs:
      - create
      - update
      - delete
    apiGroups:
      - cert-manager.io
    resources:
      - certificates
      - certificaterequests
  - verbs:
      - get
      - list
      - watch
    apiGroups:
      - cert-manager.io
    resources:
      - certificates
      - certificaterequests
      - issuers
      - clusterissuers
  - verbs:
      - get
      - list
      - watch
    apiGroups:
      - networking.k8s.io
    resources:
      - ingresses
  - verbs:
      - update
    apiGroups:
      - networking.k8s.io
    resources:
      - ingresses/finalizers
  - verbs:
      - get
      - list
      - watch
    apiGroups:
      - networking.x-k8s.io
    resources:
      - gateways
      - httproutes
  - verbs:
      - update
    apiGroups:
      - networking.x-k8s.io
    resources:
      - gateways/finalizers
      - httproutes/finalizers
  - verbs:
      - create
      - patch
    apiGroups:
      - ''
    resources:
      - events
