kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: cert-manager-controller-certificatesigningrequests
  uid: 16763a18-0d78-42e3-878c-958eaedb349a
  resourceVersion: '268137139'
  creationTimestamp: '2021-11-22T23:20:43Z'
  labels:
    app: cert-manager
    app.kubernetes.io/component: cert-manager
    app.kubernetes.io/instance: cert-manager
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: cert-manager
    app.kubernetes.io/version: v1.7.1
    helm.sh/chart: cert-manager-v1.7.1
  annotations:
    meta.helm.sh/release-name: cert-manager
    meta.helm.sh/release-namespace: cert-manager
  managedFields:
    - manager: Go-http-client
      operation: Update
      apiVersion: rbac.authorization.k8s.io/v1
      time: '2021-11-22T23:20:43Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:metadata':
          'f:annotations':
            .: {}
            'f:meta.helm.sh/release-name': {}
            'f:meta.helm.sh/release-namespace': {}
          'f:labels':
            .: {}
            'f:app': {}
            'f:app.kubernetes.io/component': {}
            'f:app.kubernetes.io/instance': {}
            'f:app.kubernetes.io/managed-by': {}
            'f:app.kubernetes.io/name': {}
            'f:app.kubernetes.io/version': {}
            'f:helm.sh/chart': {}
        'f:rules': {}
rules:
  - verbs:
      - get
      - list
      - watch
      - update
    apiGroups:
      - certificates.k8s.io
    resources:
      - certificatesigningrequests
  - verbs:
      - update
    apiGroups:
      - certificates.k8s.io
    resources:
      - certificatesigningrequests/status
  - verbs:
      - sign
    apiGroups:
      - certificates.k8s.io
    resources:
      - signers
    resourceNames:
      - issuers.cert-manager.io/*
      - clusterissuers.cert-manager.io/*
  - verbs:
      - create
    apiGroups:
      - authorization.k8s.io
    resources:
      - subjectaccessreviews
