kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: openshift-ingress-operator
  uid: 208c4ed8-6c46-4062-80cb-3dc18e818bb4
  resourceVersion: '758959270'
  creationTimestamp: '2021-05-26T19:21:51Z'
  annotations:
    include.release.openshift.io/ibm-cloud-managed: 'true'
    include.release.openshift.io/self-managed-high-availability: 'true'
    include.release.openshift.io/single-node-developer: 'true'
  ownerReferences:
    - apiVersion: config.openshift.io/v1
      kind: ClusterVersion
      name: version
      uid: 6a9b93f4-1c67-404e-b391-667669084d02
  managedFields:
    - manager: cluster-version-operator
      operation: Update
      apiVersion: rbac.authorization.k8s.io/v1
      time: '2022-06-22T17:02:31Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:metadata':
          'f:annotations':
            .: {}
            'f:include.release.openshift.io/ibm-cloud-managed': {}
            'f:include.release.openshift.io/self-managed-high-availability': {}
            'f:include.release.openshift.io/single-node-developer': {}
          'f:ownerReferences':
            .: {}
            'k:{"uid":"6a9b93f4-1c67-404e-b391-667669084d02"}': {}
        'f:rules': {}
rules:
  - verbs:
      - '*'
    apiGroups:
      - ''
    resources:
      - configmaps
      - namespaces
      - serviceaccounts
      - endpoints
      - services
      - secrets
      - pods
      - events
  - verbs:
      - create
    apiGroups:
      - ''
    resources:
      - pods/eviction
  - verbs:
      - list
    apiGroups:
      - ''
    resources:
      - nodes
  - verbs:
      - '*'
    apiGroups:
      - apps
    resources:
      - deployments
      - daemonsets
  - verbs:
      - '*'
    apiGroups:
      - policy
    resources:
      - poddisruptionbudgets
  - verbs:
      - create
      - get
      - update
    apiGroups:
      - monitoring.coreos.com
    resources:
      - servicemonitors
  - verbs:
      - create
      - get
      - list
      - watch
      - update
    apiGroups:
      - rbac.authorization.k8s.io
    resources:
      - clusterroles
      - clusterrolebindings
      - roles
      - rolebindings
  - verbs:
      - '*'
    apiGroups:
      - operator.openshift.io
    resources:
      - ingresscontrollers
      - ingresscontrollers/status
  - verbs:
      - '*'
    apiGroups:
      - ingress.operator.openshift.io
    resources:
      - dnsrecords
      - dnsrecords/status
  - verbs:
      - get
    apiGroups:
      - config.openshift.io
    resources:
      - infrastructures
      - ingresses
      - dnses
      - apiservers
      - networks
  - verbs:
      - list
      - watch
    apiGroups:
      - config.openshift.io
    resources:
      - dnses
      - infrastructures
      - ingresses
  - verbs:
      - create
      - get
      - list
      - watch
    apiGroups:
      - config.openshift.io
    resources:
      - clusteroperators
  - verbs:
      - update
    apiGroups:
      - config.openshift.io
    resources:
      - clusteroperators/status
  - verbs:
      - patch
    apiGroups:
      - config.openshift.io
    resources:
      - ingresses/status
  - verbs:
      - '*'
    apiGroups:
      - networking.k8s.io
    resources:
      - ingressclasses
  - verbs:
      - get
    apiGroups:
      - route.openshift.io
    resources:
      - routers/metrics
  - verbs:
      - create
    apiGroups:
      - authentication.k8s.io
    resources:
      - tokenreviews
  - verbs:
      - create
    apiGroups:
      - authorization.k8s.io
    resources:
      - subjectaccessreviews
  - verbs:
      - '*'
    apiGroups:
      - route.openshift.io
    resources:
      - routes
  - verbs:
      - update
    apiGroups:
      - route.openshift.io
    resources:
      - routes/status
  - verbs:
      - use
    apiGroups:
      - security.openshift.io
    resources:
      - securitycontextconstraints
    resourceNames:
      - hostnetwork
  - verbs:
      - list
      - watch
    apiGroups:
      - discovery.k8s.io
    resources:
      - endpointslices
