kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: tekton-aggregate-view
  uid: 54b933c6-2c79-4ba8-9c1d-de5d59da8fda
  resourceVersion: '773074312'
  creationTimestamp: '2022-11-30T16:11:03Z'
  labels:
    app.kubernetes.io/instance: default
    app.kubernetes.io/part-of: tekton-pipelines
    operator.tekton.dev/operand-name: tektoncd-pipelines
    rbac.authorization.k8s.io/aggregate-to-view: 'true'
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: >
      {"apiVersion":"rbac.authorization.k8s.io/v1","kind":"ClusterRole","metadata":{"labels":{"app.kubernetes.io/instance":"default","app.kubernetes.io/part-of":"tekton-pipelines","operator.tekton.dev/operand-name":"tektoncd-pipelines","rbac.authorization.k8s.io/aggregate-to-view":"true"},"name":"tekton-aggregate-view","ownerReferences":[{"apiVersion":"operator.tekton.dev/v1alpha1","blockOwnerDeletion":true,"controller":true,"kind":"TektonInstallerSet","name":"pipeline-td7lg","uid":"3b7ac7ce-3ee3-43ff-9b74-0071ab7560ce"}]},"rules":[{"apiGroups":["tekton.dev"],"resources":["tasks","taskruns","pipelines","pipelineruns","pipelineresources","conditions"],"verbs":["get","list","watch"]}]}
    manifestival: new
  ownerReferences:
    - apiVersion: operator.tekton.dev/v1alpha1
      kind: TektonInstallerSet
      name: pipeline-td7lg
      uid: 3b7ac7ce-3ee3-43ff-9b74-0071ab7560ce
      controller: true
      blockOwnerDeletion: true
  managedFields:
    - manager: manifestival
      operation: Update
      apiVersion: rbac.authorization.k8s.io/v1
      time: '2022-11-30T16:11:03Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:metadata':
          'f:annotations':
            .: {}
            'f:kubectl.kubernetes.io/last-applied-configuration': {}
            'f:manifestival': {}
          'f:labels':
            .: {}
            'f:app.kubernetes.io/instance': {}
            'f:app.kubernetes.io/part-of': {}
            'f:operator.tekton.dev/operand-name': {}
            'f:rbac.authorization.k8s.io/aggregate-to-view': {}
          'f:ownerReferences':
            .: {}
            'k:{"uid":"3b7ac7ce-3ee3-43ff-9b74-0071ab7560ce"}': {}
        'f:rules': {}
rules:
  - verbs:
      - get
      - list
      - watch
    apiGroups:
      - tekton.dev
    resources:
      - tasks
      - taskruns
      - pipelines
      - pipelineruns
      - pipelineresources
      - conditions
