kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: telemeter-client
  uid: 9cadbe0a-18f7-447c-b219-878c066f6e6d
  resourceVersion: '476161613'
  creationTimestamp: '2022-03-14T23:32:42Z'
  managedFields:
    - manager: operator
      operation: Update
      apiVersion: rbac.authorization.k8s.io/v1
      time: '2022-03-14T23:32:41Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:rules': {}
rules:
  - verbs:
      - create
    apiGroups:
      - authentication.k8s.io
    resources:
      - tokenreviews
  - verbs:
      - create
    apiGroups:
      - authorization.k8s.io
    resources:
      - subjectaccessreviews
