kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: tektonchains.operator.tekton.dev-v1alpha1-admin
  uid: fb5ebab1-96a0-4ee7-9b40-fbbe99654a22
  resourceVersion: '757693729'
  creationTimestamp: '2022-11-16T15:25:20Z'
  labels:
    olm.opgroup.permissions/aggregate-to-22e514fea180dc6f-admin: 'true'
    rbac.authorization.k8s.io/aggregate-to-admin: 'true'
  ownerReferences:
    - apiVersion: apiextensions.k8s.io/v1
      kind: CustomResourceDefinition
      name: tektonchains.operator.tekton.dev
      uid: 07f9ac58-f66c-4f58-8dff-e34ae2045bdf
      controller: false
      blockOwnerDeletion: false
  managedFields:
    - manager: olm
      operation: Update
      apiVersion: rbac.authorization.k8s.io/v1
      time: '2022-11-16T15:25:20Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:metadata':
          'f:labels':
            .: {}
            'f:olm.opgroup.permissions/aggregate-to-22e514fea180dc6f-admin': {}
            'f:rbac.authorization.k8s.io/aggregate-to-admin': {}
          'f:ownerReferences':
            .: {}
            'k:{"uid":"07f9ac58-f66c-4f58-8dff-e34ae2045bdf"}': {}
        'f:rules': {}
rules:
  - verbs:
      - '*'
    apiGroups:
      - operator.tekton.dev
    resources:
      - tektonchains
