kind: Pod
apiVersion: v1
metadata:
  generateName: openshift-web-console-9f5bfb5c-
  annotations:
    cni.projectcalico.org/containerID: 1d9eb6e0b0b86d422f2b0e5e12011397412116e3a4bcd8f4f37f77cc44cb3b6d
    cni.projectcalico.org/podIP: 172.17.36.175/32
    cni.projectcalico.org/podIPs: 172.17.36.175/32
    k8s.v1.cni.cncf.io/network-status: |-
      [{
          "name": "k8s-pod-network",
          "ips": [
              "172.17.36.175"
          ],
          "default": true,
          "dns": {}
      }]
    k8s.v1.cni.cncf.io/networks-status: |-
      [{
          "name": "k8s-pod-network",
          "ips": [
              "172.17.36.175"
          ],
          "default": true,
          "dns": {}
      }]
    openshift.io/scc: restricted-v2
    seccomp.security.alpha.kubernetes.io/pod: runtime/default
  resourceVersion: '809977926'
  name: openshift-web-console-9f5bfb5c-xv4wf
  uid: 1dcda792-d8a5-4fb9-9895-a8df3fc96680
  creationTimestamp: '2023-01-04T11:20:50Z'
  managedFields:
    - manager: kube-controller-manager
      operation: Update
      apiVersion: v1
      time: '2023-01-04T11:20:50Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:metadata':
          'f:generateName': {}
          'f:labels':
            .: {}
            'f:app': {}
            'f:pod-template-hash': {}
          'f:ownerReferences':
            .: {}
            'k:{"uid":"95818cfc-7c8d-4700-be4d-cabcfa63d86c"}': {}
        'f:spec':
          'f:volumes':
            .: {}
            'k:{"name":"console-logo"}':
              .: {}
              'f:configMap':
                .: {}
                'f:defaultMode': {}
                'f:name': {}
              'f:name': {}
          'f:containers':
            'k:{"name":"console"}':
              'f:image': {}
              'f:volumeMounts':
                .: {}
                'k:{"mountPath":"/var/logo/"}':
                  .: {}
                  'f:mountPath': {}
                  'f:name': {}
              'f:terminationMessagePolicy': {}
              .: {}
              'f:resources':
                .: {}
                'f:limits':
                  .: {}
                  'f:cpu': {}
                  'f:ephemeral-storage': {}
                  'f:memory': {}
                'f:requests':
                  .: {}
                  'f:cpu': {}
                  'f:ephemeral-storage': {}
                  'f:memory': {}
              'f:command': {}
              'f:livenessProbe':
                .: {}
                'f:failureThreshold': {}
                'f:httpGet':
                  .: {}
                  'f:path': {}
                  'f:port': {}
                  'f:scheme': {}
                'f:initialDelaySeconds': {}
                'f:periodSeconds': {}
                'f:successThreshold': {}
                'f:timeoutSeconds': {}
              'f:readinessProbe':
                .: {}
                'f:failureThreshold': {}
                'f:httpGet':
                  .: {}
                  'f:path': {}
                  'f:port': {}
                  'f:scheme': {}
                'f:periodSeconds': {}
                'f:successThreshold': {}
                'f:timeoutSeconds': {}
              'f:terminationMessagePath': {}
              'f:imagePullPolicy': {}
              'f:ports':
                .: {}
                'k:{"containerPort":8443,"protocol":"TCP"}':
                  .: {}
                  'f:containerPort': {}
                  'f:name': {}
                  'f:protocol': {}
              'f:name': {}
            'k:{"name":"openshift-web-console"}':
              'f:image': {}
              'f:terminationMessagePolicy': {}
              .: {}
              'f:resources':
                .: {}
                'f:limits':
                  .: {}
                  'f:cpu': {}
                  'f:ephemeral-storage': {}
                  'f:memory': {}
                'f:requests':
                  .: {}
                  'f:cpu': {}
                  'f:ephemeral-storage': {}
                  'f:memory': {}
              'f:livenessProbe':
                .: {}
                'f:failureThreshold': {}
                'f:httpGet':
                  .: {}
                  'f:path': {}
                  'f:port': {}
                  'f:scheme': {}
                'f:initialDelaySeconds': {}
                'f:periodSeconds': {}
                'f:successThreshold': {}
                'f:timeoutSeconds': {}
              'f:env':
                .: {}
                'k:{"name":"CONSOLE"}':
                  .: {}
                  'f:name': {}
                  'f:value': {}
                'k:{"name":"PASSWORD"}':
                  .: {}
                  'f:name': {}
                  'f:value': {}
                'k:{"name":"PROXY"}':
                  .: {}
                  'f:name': {}
                  'f:value': {}
                'k:{"name":"USERNAME"}':
                  .: {}
                  'f:name': {}
                  'f:value': {}
              'f:readinessProbe':
                .: {}
                'f:failureThreshold': {}
                'f:httpGet':
                  .: {}
                  'f:path': {}
                  'f:port': {}
                  'f:scheme': {}
                'f:periodSeconds': {}
                'f:successThreshold': {}
                'f:timeoutSeconds': {}
              'f:terminationMessagePath': {}
              'f:imagePullPolicy': {}
              'f:ports':
                .: {}
                'k:{"containerPort":8000,"protocol":"TCP"}':
                  .: {}
                  'f:containerPort': {}
                  'f:name': {}
                  'f:protocol': {}
              'f:name': {}
          'f:dnsPolicy': {}
          'f:tolerations': {}
          'f:serviceAccount': {}
          'f:restartPolicy': {}
          'f:schedulerName': {}
          'f:terminationGracePeriodSeconds': {}
          'f:serviceAccountName': {}
          'f:enableServiceLinks': {}
          'f:securityContext': {}
    - manager: Go-http-client
      operation: Update
      apiVersion: v1
      time: '2023-01-04T11:20:51Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:metadata':
          'f:annotations':
            'f:cni.projectcalico.org/containerID': {}
            'f:cni.projectcalico.org/podIP': {}
            'f:cni.projectcalico.org/podIPs': {}
      subresource: status
    - manager: multus
      operation: Update
      apiVersion: v1
      time: '2023-01-04T11:20:52Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:metadata':
          'f:annotations':
            'f:k8s.v1.cni.cncf.io/network-status': {}
            'f:k8s.v1.cni.cncf.io/networks-status': {}
      subresource: status
    - manager: kubelet
      operation: Update
      apiVersion: v1
      time: '2023-01-04T11:20:58Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:status':
          'f:conditions':
            'k:{"type":"ContainersReady"}':
              .: {}
              'f:lastProbeTime': {}
              'f:lastTransitionTime': {}
              'f:status': {}
              'f:type': {}
            'k:{"type":"Initialized"}':
              .: {}
              'f:lastProbeTime': {}
              'f:lastTransitionTime': {}
              'f:status': {}
              'f:type': {}
            'k:{"type":"Ready"}':
              .: {}
              'f:lastProbeTime': {}
              'f:lastTransitionTime': {}
              'f:status': {}
              'f:type': {}
          'f:containerStatuses': {}
          'f:hostIP': {}
          'f:phase': {}
          'f:podIP': {}
          'f:podIPs':
            .: {}
            'k:{"ip":"172.17.36.175"}':
              .: {}
              'f:ip': {}
          'f:startTime': {}
      subresource: status
  namespace: sn-labs-husseinashah
  ownerReferences:
    - apiVersion: apps/v1
      kind: ReplicaSet
      name: openshift-web-console-9f5bfb5c
      uid: 95818cfc-7c8d-4700-be4d-cabcfa63d86c
      controller: true
      blockOwnerDeletion: true
  labels:
    app: openshift-web-console
    pod-template-hash: 9f5bfb5c
spec:
  restartPolicy: Always
  serviceAccountName: husseinashah
  priority: 1
  schedulerName: default-scheduler
  enableServiceLinks: true
  terminationGracePeriodSeconds: 30
  preemptionPolicy: PreemptLowerPriority
  nodeName: 10.241.0.46
  securityContext:
    seLinuxOptions:
      level: 's0:c31,c10'
    fsGroup: 1000950000
    seccompProfile:
      type: RuntimeDefault
  containers:
    - resources:
        limits:
          cpu: 50m
          ephemeral-storage: 1Gi
          memory: 256Mi
        requests:
          cpu: 10m
          ephemeral-storage: 512Mi
          memory: 100Mi
      readinessProbe:
        httpGet:
          path: /health
          port: 8000
          scheme: HTTP
        timeoutSeconds: 1
        periodSeconds: 10
        successThreshold: 1
        failureThreshold: 3
      terminationMessagePath: /dev/termination-log
      name: openshift-web-console
      livenessProbe:
        httpGet:
          path: /health
          port: 8000
          scheme: HTTP
        initialDelaySeconds: 150
        timeoutSeconds: 1
        periodSeconds: 10
        successThreshold: 1
        failureThreshold: 3
      env:
        - name: PROXY
          value: husseinashah-console.openshift-sandbox.labs.cognitiveclass.ai
        - name: USERNAME
          value: husseinashah
        - name: PASSWORD
          value: aHVzc2VpbmFzaGFo
        - name: CONSOLE
          value: 'localhost:8443'
      securityContext:
        capabilities:
          drop:
            - ALL
        runAsUser: 1000950000
        runAsNonRoot: true
        allowPrivilegeEscalation: false
      ports:
        - name: http
          containerPort: 8000
          protocol: TCP
      imagePullPolicy: IfNotPresent
      volumeMounts:
        - name: kube-api-access-cdqxr
          readOnly: true
          mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      terminationMessagePolicy: FallbackToLogsOnError
      image: 'docker.io/doctorqubit/basic-auth-proxy:0.1.13'
    - resources:
        limits:
          cpu: 50m
          ephemeral-storage: 1Gi
          memory: 256Mi
        requests:
          cpu: 10m
          ephemeral-storage: 512Mi
          memory: 100Mi
      readinessProbe:
        httpGet:
          path: /health
          port: 8443
          scheme: HTTP
        timeoutSeconds: 1
        periodSeconds: 10
        successThreshold: 1
        failureThreshold: 3
      terminationMessagePath: /dev/termination-log
      name: console
      command:
        - /opt/bridge/bin/bridge
        - '--public-dir=/opt/bridge/static'
        - >-
          --base-address=https://husseinashah-console.openshift-sandbox.labs.cognitiveclass.ai
        - '--user-auth=disabled'
        - '--listen=http://0.0.0.0:8443'
        - '--custom-logo-file=/var/logo/console-logo.svg'
        - '--branding=openshift'
        - '--custom-product-name=Skills Network OpenShift Lab'
      livenessProbe:
        httpGet:
          path: /health
          port: 8443
          scheme: HTTP
        initialDelaySeconds: 150
        timeoutSeconds: 1
        periodSeconds: 10
        successThreshold: 1
        failureThreshold: 3
      securityContext:
        capabilities:
          drop:
            - ALL
        runAsUser: 1000950000
        runAsNonRoot: true
        allowPrivilegeEscalation: false
      ports:
        - name: http
          containerPort: 8443
          protocol: TCP
      imagePullPolicy: IfNotPresent
      volumeMounts:
        - name: console-logo
          mountPath: /var/logo/
        - name: kube-api-access-cdqxr
          readOnly: true
          mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      terminationMessagePolicy: FallbackToLogsOnError
      image: >-
        quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:33724b503bea2463abe308dd9fb8ad69d9e8946815219fe2e4c8c33d0716bb1c
  serviceAccount: husseinashah
  volumes:
    - name: console-logo
      configMap:
        name: console-logo
        defaultMode: 420
    - name: kube-api-access-cdqxr
      projected:
        sources:
          - serviceAccountToken:
              expirationSeconds: 3607
              path: token
          - configMap:
              name: kube-root-ca.crt
              items:
                - key: ca.crt
                  path: ca.crt
          - downwardAPI:
              items:
                - path: namespace
                  fieldRef:
                    apiVersion: v1
                    fieldPath: metadata.namespace
          - configMap:
              name: openshift-service-ca.crt
              items:
                - key: service-ca.crt
                  path: service-ca.crt
        defaultMode: 420
  dnsPolicy: ClusterFirst
  tolerations:
    - key: node-role.kubernetes.io/master
      operator: Exists
      effect: NoSchedule
    - key: node.kubernetes.io/unreachable
      operator: Exists
      effect: NoExecute
      tolerationSeconds: 120
    - key: node.kubernetes.io/not-reachable
      operator: Exists
      effect: NoExecute
      tolerationSeconds: 120
    - key: node.kubernetes.io/not-ready
      operator: Exists
      effect: NoExecute
      tolerationSeconds: 300
    - key: node.kubernetes.io/memory-pressure
      operator: Exists
      effect: NoSchedule
  priorityClassName: normal
status:
  phase: Running
  conditions:
    - type: Initialized
      status: 'True'
      lastProbeTime: null
      lastTransitionTime: '2023-01-04T11:20:50Z'
    - type: Ready
      status: 'True'
      lastProbeTime: null
      lastTransitionTime: '2023-01-04T11:20:58Z'
    - type: ContainersReady
      status: 'True'
      lastProbeTime: null
      lastTransitionTime: '2023-01-04T11:20:58Z'
    - type: PodScheduled
      status: 'True'
      lastProbeTime: null
      lastTransitionTime: '2023-01-04T11:20:50Z'
  hostIP: 10.241.0.46
  podIP: 172.17.36.175
  podIPs:
    - ip: 172.17.36.175
  startTime: '2023-01-04T11:20:50Z'
  containerStatuses:
    - restartCount: 0
      started: true
      ready: true
      name: console
      state:
        running:
          startedAt: '2023-01-04T11:20:55Z'
      imageID: >-
        quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:33724b503bea2463abe308dd9fb8ad69d9e8946815219fe2e4c8c33d0716bb1c
      image: >-
        quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:33724b503bea2463abe308dd9fb8ad69d9e8946815219fe2e4c8c33d0716bb1c
      lastState: {}
      containerID: 'cri-o://4c0492636891fd7f5a4723a1ef68e01285de0790aa8c85a6a40e71bbf651aed7'
    - restartCount: 0
      started: true
      ready: true
      name: openshift-web-console
      state:
        running:
          startedAt: '2023-01-04T11:20:54Z'
      imageID: >-
        docker.io/doctorqubit/basic-auth-proxy@sha256:f3cd15bd3584d97c03a0f5c79cb28ece58ca6d6dd549700068cc878893427e01
      image: 'docker.io/doctorqubit/basic-auth-proxy:0.1.13'
      lastState: {}
      containerID: 'cri-o://b1b6c5b7305151f20786d5e604ff90429d8e795d9be36960f30e753e04115336'
  qosClass: Burstable
