kind: Pod
apiVersion: v1
metadata:
  generateName: redis-slave-d474ccd84-
  annotations:
    cni.projectcalico.org/containerID: 0b042e616fc531f0594524dd06d106d76ca53f682cf57f779f41d1f66cd21194
    cni.projectcalico.org/podIP: 172.17.18.8/32
    cni.projectcalico.org/podIPs: 172.17.18.8/32
    k8s.v1.cni.cncf.io/network-status: |-
      [{
          "name": "k8s-pod-network",
          "ips": [
              "172.17.18.8"
          ],
          "default": true,
          "dns": {}
      }]
    k8s.v1.cni.cncf.io/networks-status: |-
      [{
          "name": "k8s-pod-network",
          "ips": [
              "172.17.18.8"
          ],
          "default": true,
          "dns": {}
      }]
    kubernetes.io/limit-ranger: >-
      LimitRanger plugin set: cpu, ephemeral-storage, memory request for
      container redis-slave; cpu, ephemeral-storage, memory limit for container
      redis-slave
    openshift.io/scc: restricted-v2
    seccomp.security.alpha.kubernetes.io/pod: runtime/default
  resourceVersion: '810391207'
  name: redis-slave-d474ccd84-2gkl9
  uid: eb3c03c4-d730-4f78-855c-3553e6665289
  creationTimestamp: '2023-01-04T20:34:01Z'
  managedFields:
    - manager: kube-controller-manager
      operation: Update
      apiVersion: v1
      time: '2023-01-04T20:34:01Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:metadata':
          'f:generateName': {}
          'f:labels':
            .: {}
            'f:app': {}
            'f:pod-template-hash': {}
            'f:role': {}
          'f:ownerReferences':
            .: {}
            'k:{"uid":"0e32707c-53ba-478a-8bd8-b34f4cb32e6f"}': {}
        'f:spec':
          'f:containers':
            'k:{"name":"redis-slave"}':
              'f:image': {}
              'f:volumeMounts':
                .: {}
                'k:{"mountPath":"/data"}':
                  .: {}
                  'f:mountPath': {}
                  'f:name': {}
              'f:terminationMessagePolicy': {}
              .: {}
              'f:resources': {}
              'f:args': {}
              'f:command': {}
              'f:terminationMessagePath': {}
              'f:imagePullPolicy': {}
              'f:ports':
                .: {}
                'k:{"containerPort":6379,"protocol":"TCP"}':
                  .: {}
                  'f:containerPort': {}
                  'f:name': {}
                  'f:protocol': {}
              'f:name': {}
          'f:dnsPolicy': {}
          'f:enableServiceLinks': {}
          'f:restartPolicy': {}
          'f:schedulerName': {}
          'f:securityContext': {}
          'f:terminationGracePeriodSeconds': {}
          'f:volumes':
            .: {}
            'k:{"name":"redis-storage"}':
              .: {}
              'f:emptyDir': {}
              'f:name': {}
    - manager: Go-http-client
      operation: Update
      apiVersion: v1
      time: '2023-01-04T20:34:02Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:metadata':
          'f:annotations':
            'f:cni.projectcalico.org/containerID': {}
            'f:cni.projectcalico.org/podIP': {}
            'f:cni.projectcalico.org/podIPs': {}
      subresource: status
    - manager: multus
      operation: Update
      apiVersion: v1
      time: '2023-01-04T20:34:02Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:metadata':
          'f:annotations':
            'f:k8s.v1.cni.cncf.io/network-status': {}
            'f:k8s.v1.cni.cncf.io/networks-status': {}
      subresource: status
    - manager: kubelet
      operation: Update
      apiVersion: v1
      time: '2023-01-04T20:34:03Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:status':
          'f:conditions':
            'k:{"type":"ContainersReady"}':
              .: {}
              'f:lastProbeTime': {}
              'f:lastTransitionTime': {}
              'f:status': {}
              'f:type': {}
            'k:{"type":"Initialized"}':
              .: {}
              'f:lastProbeTime': {}
              'f:lastTransitionTime': {}
              'f:status': {}
              'f:type': {}
            'k:{"type":"Ready"}':
              .: {}
              'f:lastProbeTime': {}
              'f:lastTransitionTime': {}
              'f:status': {}
              'f:type': {}
          'f:containerStatuses': {}
          'f:hostIP': {}
          'f:phase': {}
          'f:podIP': {}
          'f:podIPs':
            .: {}
            'k:{"ip":"172.17.18.8"}':
              .: {}
              'f:ip': {}
          'f:startTime': {}
      subresource: status
  namespace: sn-labs-husseinashah
  ownerReferences:
    - apiVersion: apps/v1
      kind: ReplicaSet
      name: redis-slave-d474ccd84
      uid: 0e32707c-53ba-478a-8bd8-b34f4cb32e6f
      controller: true
      blockOwnerDeletion: true
  labels:
    app: redis
    pod-template-hash: d474ccd84
    role: slave
spec:
  restartPolicy: Always
  serviceAccountName: default
  imagePullSecrets:
    - name: icr
    - name: dh
    - name: default-dockercfg-g7cc8
  priority: 1
  schedulerName: default-scheduler
  enableServiceLinks: true
  terminationGracePeriodSeconds: 30
  preemptionPolicy: PreemptLowerPriority
  nodeName: 10.241.0.47
  securityContext:
    seLinuxOptions:
      level: 's0:c31,c10'
    fsGroup: 1000950000
    seccompProfile:
      type: RuntimeDefault
  containers:
    - resources:
        limits:
          cpu: 500m
          ephemeral-storage: 5Gi
          memory: 512Mi
        requests:
          cpu: 200m
          ephemeral-storage: 512Mi
          memory: 128Mi
      terminationMessagePath: /dev/termination-log
      name: redis-slave
      command:
        - /bin/sh
      securityContext:
        capabilities:
          drop:
            - ALL
        runAsUser: 1000950000
        runAsNonRoot: true
        allowPrivilegeEscalation: false
      ports:
        - name: redis-server
          containerPort: 6379
          protocol: TCP
      imagePullPolicy: IfNotPresent
      volumeMounts:
        - name: redis-storage
          mountPath: /data
        - name: kube-api-access-4vqn4
          readOnly: true
          mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      terminationMessagePolicy: File
      image: 'redis:5.0.5'
      args:
        - '-c'
        - redis-server --slaveof redis-master 6379
  serviceAccount: default
  volumes:
    - name: redis-storage
      emptyDir: {}
    - name: kube-api-access-4vqn4
      projected:
        sources:
          - serviceAccountToken:
              expirationSeconds: 3607
              path: token
          - configMap:
              name: kube-root-ca.crt
              items:
                - key: ca.crt
                  path: ca.crt
          - downwardAPI:
              items:
                - path: namespace
                  fieldRef:
                    apiVersion: v1
                    fieldPath: metadata.namespace
          - configMap:
              name: openshift-service-ca.crt
              items:
                - key: service-ca.crt
                  path: service-ca.crt
        defaultMode: 420
  dnsPolicy: ClusterFirst
  tolerations:
    - key: node.kubernetes.io/not-ready
      operator: Exists
      effect: NoExecute
      tolerationSeconds: 300
    - key: node.kubernetes.io/unreachable
      operator: Exists
      effect: NoExecute
      tolerationSeconds: 300
    - key: node.kubernetes.io/memory-pressure
      operator: Exists
      effect: NoSchedule
  priorityClassName: normal
status:
  phase: Running
  conditions:
    - type: Initialized
      status: 'True'
      lastProbeTime: null
      lastTransitionTime: '2023-01-04T20:34:01Z'
    - type: Ready
      status: 'True'
      lastProbeTime: null
      lastTransitionTime: '2023-01-04T20:34:03Z'
    - type: ContainersReady
      status: 'True'
      lastProbeTime: null
      lastTransitionTime: '2023-01-04T20:34:03Z'
    - type: PodScheduled
      status: 'True'
      lastProbeTime: null
      lastTransitionTime: '2023-01-04T20:34:01Z'
  hostIP: 10.241.0.47
  podIP: 172.17.18.8
  podIPs:
    - ip: 172.17.18.8
  startTime: '2023-01-04T20:34:01Z'
  containerStatuses:
    - restartCount: 0
      started: true
      ready: true
      name: redis-slave
      state:
        running:
          startedAt: '2023-01-04T20:34:02Z'
      imageID: >-
        docker.io/library/redis@sha256:5dcccb533dc0deacce4a02fe9035134576368452db0b4323b98a4b2ba2d3b302
      image: 'docker.io/library/redis:5.0.5'
      lastState: {}
      containerID: 'cri-o://856d045a2f1aed7367e68f524071ad8cb428cef93eeb67a24aafa2d5e07920d1'
  qosClass: Burstable
