kind: Pod
apiVersion: v1
metadata:
  generateName: guestbook-5bbb49578f-
  annotations:
    cni.projectcalico.org/containerID: f9ad3f79f50dd4befee95505199604d115ad7eeee7fc53c42489a907ebde8ce0
    cni.projectcalico.org/podIP: 172.17.9.166/32
    cni.projectcalico.org/podIPs: 172.17.9.166/32
    k8s.v1.cni.cncf.io/network-status: |-
      [{
          "name": "k8s-pod-network",
          "ips": [
              "172.17.9.166"
          ],
          "default": true,
          "dns": {}
      }]
    k8s.v1.cni.cncf.io/networks-status: |-
      [{
          "name": "k8s-pod-network",
          "ips": [
              "172.17.9.166"
          ],
          "default": true,
          "dns": {}
      }]
    kubernetes.io/limit-ranger: >-
      LimitRanger plugin set: ephemeral-storage, memory request for container
      guestbook; ephemeral-storage, memory limit for container guestbook
    openshift.io/scc: restricted-v2
    seccomp.security.alpha.kubernetes.io/pod: runtime/default
  resourceVersion: '810334692'
  name: guestbook-5bbb49578f-6p58n
  uid: a80714c6-ca8d-49db-b232-c1b49e9f9637
  creationTimestamp: '2023-01-04T19:18:39Z'
  managedFields:
    - manager: kube-controller-manager
      operation: Update
      apiVersion: v1
      time: '2023-01-04T19:18:39Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:metadata':
          'f:generateName': {}
          'f:labels':
            .: {}
            'f:app': {}
            'f:pod-template-hash': {}
          'f:ownerReferences':
            .: {}
            'k:{"uid":"7ee70403-ca5b-4a0e-93c2-7e3a4f77e6ea"}': {}
        'f:spec':
          'f:containers':
            'k:{"name":"guestbook"}':
              .: {}
              'f:image': {}
              'f:imagePullPolicy': {}
              'f:name': {}
              'f:ports':
                .: {}
                'k:{"containerPort":3000,"protocol":"TCP"}':
                  .: {}
                  'f:containerPort': {}
                  'f:name': {}
                  'f:protocol': {}
              'f:resources':
                .: {}
                'f:limits':
                  .: {}
                  'f:cpu': {}
                'f:requests':
                  .: {}
                  'f:cpu': {}
              'f:terminationMessagePath': {}
              'f:terminationMessagePolicy': {}
          'f:dnsPolicy': {}
          'f:enableServiceLinks': {}
          'f:restartPolicy': {}
          'f:schedulerName': {}
          'f:securityContext': {}
          'f:terminationGracePeriodSeconds': {}
    - manager: Go-http-client
      operation: Update
      apiVersion: v1
      time: '2023-01-04T19:18:40Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:metadata':
          'f:annotations':
            'f:cni.projectcalico.org/containerID': {}
            'f:cni.projectcalico.org/podIP': {}
            'f:cni.projectcalico.org/podIPs': {}
      subresource: status
    - manager: multus
      operation: Update
      apiVersion: v1
      time: '2023-01-04T19:18:41Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:metadata':
          'f:annotations':
            'f:k8s.v1.cni.cncf.io/network-status': {}
            'f:k8s.v1.cni.cncf.io/networks-status': {}
      subresource: status
    - manager: kubelet
      operation: Update
      apiVersion: v1
      time: '2023-01-04T19:19:02Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:status':
          'f:conditions':
            'k:{"type":"ContainersReady"}':
              .: {}
              'f:lastProbeTime': {}
              'f:lastTransitionTime': {}
              'f:status': {}
              'f:type': {}
            'k:{"type":"Initialized"}':
              .: {}
              'f:lastProbeTime': {}
              'f:lastTransitionTime': {}
              'f:status': {}
              'f:type': {}
            'k:{"type":"Ready"}':
              .: {}
              'f:lastProbeTime': {}
              'f:lastTransitionTime': {}
              'f:status': {}
              'f:type': {}
          'f:containerStatuses': {}
          'f:hostIP': {}
          'f:phase': {}
          'f:podIP': {}
          'f:podIPs':
            .: {}
            'k:{"ip":"172.17.9.166"}':
              .: {}
              'f:ip': {}
          'f:startTime': {}
      subresource: status
  namespace: sn-labs-husseinashah
  ownerReferences:
    - apiVersion: apps/v1
      kind: ReplicaSet
      name: guestbook-5bbb49578f
      uid: 7ee70403-ca5b-4a0e-93c2-7e3a4f77e6ea
      controller: true
      blockOwnerDeletion: true
  labels:
    app: guestbook
    pod-template-hash: 5bbb49578f
spec:
  restartPolicy: Always
  serviceAccountName: default
  imagePullSecrets:
    - name: icr
    - name: dh
    - name: default-dockercfg-g7cc8
  priority: 1
  schedulerName: default-scheduler
  enableServiceLinks: true
  terminationGracePeriodSeconds: 30
  preemptionPolicy: PreemptLowerPriority
  nodeName: 10.241.0.45
  securityContext:
    seLinuxOptions:
      level: 's0:c31,c10'
    fsGroup: 1000950000
    seccompProfile:
      type: RuntimeDefault
  containers:
    - resources:
        limits:
          cpu: 5m
          ephemeral-storage: 5Gi
          memory: 512Mi
        requests:
          cpu: 2m
          ephemeral-storage: 512Mi
          memory: 128Mi
      terminationMessagePath: /dev/termination-log
      name: guestbook
      securityContext:
        capabilities:
          drop:
            - ALL
        runAsUser: 1000950000
        runAsNonRoot: true
        allowPrivilegeEscalation: false
      ports:
        - name: http
          containerPort: 3000
          protocol: TCP
      imagePullPolicy: Always
      volumeMounts:
        - name: kube-api-access-csdrj
          readOnly: true
          mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      terminationMessagePolicy: File
      image: 'us.icr.io/sn-labs-husseinashah/guestbook:v1'
  serviceAccount: default
  volumes:
    - name: kube-api-access-csdrj
      projected:
        sources:
          - serviceAccountToken:
              expirationSeconds: 3607
              path: token
          - configMap:
              name: kube-root-ca.crt
              items:
                - key: ca.crt
                  path: ca.crt
          - downwardAPI:
              items:
                - path: namespace
                  fieldRef:
                    apiVersion: v1
                    fieldPath: metadata.namespace
          - configMap:
              name: openshift-service-ca.crt
              items:
                - key: service-ca.crt
                  path: service-ca.crt
        defaultMode: 420
  dnsPolicy: ClusterFirst
  tolerations:
    - key: node.kubernetes.io/not-ready
      operator: Exists
      effect: NoExecute
      tolerationSeconds: 300
    - key: node.kubernetes.io/unreachable
      operator: Exists
      effect: NoExecute
      tolerationSeconds: 300
    - key: node.kubernetes.io/memory-pressure
      operator: Exists
      effect: NoSchedule
  priorityClassName: normal
status:
  phase: Running
  conditions:
    - type: Initialized
      status: 'True'
      lastProbeTime: null
      lastTransitionTime: '2023-01-04T19:18:39Z'
    - type: Ready
      status: 'True'
      lastProbeTime: null
      lastTransitionTime: '2023-01-04T19:19:02Z'
    - type: ContainersReady
      status: 'True'
      lastProbeTime: null
      lastTransitionTime: '2023-01-04T19:19:02Z'
    - type: PodScheduled
      status: 'True'
      lastProbeTime: null
      lastTransitionTime: '2023-01-04T19:18:39Z'
  hostIP: 10.241.0.45
  podIP: 172.17.9.166
  podIPs:
    - ip: 172.17.9.166
  startTime: '2023-01-04T19:18:39Z'
  containerStatuses:
    - restartCount: 0
      started: true
      ready: true
      name: guestbook
      state:
        running:
          startedAt: '2023-01-04T19:19:01Z'
      imageID: >-
        us.icr.io/sn-labs-husseinashah/guestbook@sha256:46fd17e7ac1f4dd47ac59e6a5dbd38b3b5b86266447bfba83c88b25220194dd5
      image: 'us.icr.io/sn-labs-husseinashah/guestbook:v1'
      lastState: {}
      containerID: 'cri-o://f8e0e88ac776dca035c73ad36343602cba787ed01c9f8b7df29945b3d9153142'
  qosClass: Burstable
