name: nodejs
version: 0.1
description: An example Node.js application for RP1 - Kubernetes Hardening
keywords:
- quickstart
- nodejs
home: https://access.redhat.com
sources:
- https://github.com/husseinahmed-dev/Research-Project-1-Kubernetes-Hardening/tree/main/applications/5_APP%20(nodejs-ex)
