apiVersion: v1
kind: Pod
metadata:
  name: hello-sne
spec:
  containers:
  - name: hello-sne
    image: us.icr.io/<my_namespace>/hello-sne:1
    ports:
    - containerPort: 8080
  imagePullSecrets:
  - name: icr
