kind: Service
apiVersion: v1
metadata:
  name: rp1-5app-nodejs
  namespace: sn-labs-husseinashah
  uid: a4dfd3ec-7ae9-4feb-b54b-acbbf6957c9f
  resourceVersion: '810067272'
  creationTimestamp: '2023-01-04T13:19:55Z'
  labels:
    app: rp1-5app-nodejs
    app.kubernetes.io/component: rp1-5app-nodejs
    app.kubernetes.io/instance: rp1-5app-nodejs
    app.kubernetes.io/name: nodejs
    app.kubernetes.io/part-of: research-project-1-kubernetes-hardening-git-app
    app.openshift.io/runtime: nodejs
    app.openshift.io/runtime-version: 16-ubi8
  annotations:
    app.openshift.io/vcs-ref: ''
    app.openshift.io/vcs-uri: >-
      https://github.com/husseinahmed-dev/Research-Project-1-Kubernetes-Hardening.git
    openshift.io/generated-by: OpenShiftWebConsole
  managedFields:
    - manager: Mozilla
      operation: Update
      apiVersion: v1
      time: '2023-01-04T13:19:55Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:metadata':
          'f:annotations':
            .: {}
            'f:app.openshift.io/vcs-ref': {}
            'f:app.openshift.io/vcs-uri': {}
            'f:openshift.io/generated-by': {}
          'f:labels':
            .: {}
            'f:app': {}
            'f:app.kubernetes.io/component': {}
            'f:app.kubernetes.io/instance': {}
            'f:app.kubernetes.io/name': {}
            'f:app.kubernetes.io/part-of': {}
            'f:app.openshift.io/runtime': {}
            'f:app.openshift.io/runtime-version': {}
        'f:spec':
          'f:internalTrafficPolicy': {}
          'f:ports':
            .: {}
            'k:{"port":8080,"protocol":"TCP"}':
              .: {}
              'f:name': {}
              'f:port': {}
              'f:protocol': {}
              'f:targetPort': {}
          'f:selector': {}
          'f:sessionAffinity': {}
          'f:type': {}
spec:
  clusterIP: 172.21.190.82
  ipFamilies:
    - IPv4
  ports:
    - name: 8080-tcp
      protocol: TCP
      port: 8080
      targetPort: 8080
  internalTrafficPolicy: Cluster
  clusterIPs:
    - 172.21.190.82
  type: ClusterIP
  ipFamilyPolicy: SingleStack
  sessionAffinity: None
  selector:
    app: rp1-5app-nodejs
    deploymentconfig: rp1-5app-nodejs
status:
  loadBalancer: {}
