kind: ResourceQuota
apiVersion: v1
metadata:
  name: husseinashah-resourcequota
  namespace: sn-labs-husseinashah
  uid: d6700f61-ab9d-41eb-9716-24d5b81402f5
  resourceVersion: '810086340'
  creationTimestamp: '2023-01-04T11:20:50Z'
  managedFields:
    - manager: unknown
      operation: Update
      apiVersion: v1
      time: '2023-01-04T11:20:50Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:spec':
          'f:hard':
            'f:ibmc-vpc-block-metro-retain-general-purpose.storageclass.storage.k8s.io/persistentvolumeclaims': {}
            'f:ibmc-vpc-block-metro-custom.storageclass.storage.k8s.io/persistentvolumeclaims': {}
            'f:ibmc-vpc-block-metro-5iops-tier.storageclass.storage.k8s.io/persistentvolumeclaims': {}
            'f:pods': {}
            'f:limits.memory': {}
            'f:ibmc-vpcblock-odf-ret-10iops.storageclass.storage.k8s.io/persistentvolumeclaims': {}
            'f:ibmc-vpc-block-retain-10iops-tier.storageclass.storage.k8s.io/persistentvolumeclaims': {}
            'f:limits.cpu': {}
            'f:ibmc-vpcblock-odf-general.storageclass.storage.k8s.io/persistentvolumeclaims': {}
            'f:ibmc-vpcblock-odf-custom.storageclass.storage.k8s.io/persistentvolumeclaims': {}
            'f:ibmc-vpc-block-retain-custom.storageclass.storage.k8s.io/persistentvolumeclaims': {}
            'f:ibmc-vpc-block-general-purpose.storageclass.storage.k8s.io/persistentvolumeclaims': {}
            'f:ibmc-vpc-block-retain-5iops-tier.storageclass.storage.k8s.io/persistentvolumeclaims': {}
            'f:limits.ephemeral-storage': {}
            .: {}
            'f:ibmc-vpc-block-metro-10iops-tier.storageclass.storage.k8s.io/persistentvolumeclaims': {}
            'f:ibmc-vpcblock-odf-5iops.storageclass.storage.k8s.io/persistentvolumeclaims': {}
            'f:ibmc-vpcblock-odf-10iops.storageclass.storage.k8s.io/persistentvolumeclaims': {}
            'f:ibmc-vpc-block-metro-retain-10iops-tier.storageclass.storage.k8s.io/persistentvolumeclaims': {}
            'f:ibmc-vpcblock-odf-ret-general.storageclass.storage.k8s.io/persistentvolumeclaims': {}
            'f:requests.cpu': {}
            'f:ibmc-vpc-block-retain-general-purpose.storageclass.storage.k8s.io/persistentvolumeclaims': {}
            'f:ibmc-vpc-block-5iops-tier.storageclass.storage.k8s.io/persistentvolumeclaims': {}
            'f:ibmc-vpc-block-custom.storageclass.storage.k8s.io/persistentvolumeclaims': {}
            'f:requests.ephemeral-storage': {}
            'f:requests.memory': {}
            'f:skills-network-learner.storageclass.storage.k8s.io/persistentvolumeclaims': {}
            'f:ibmc-vpc-block-10iops-tier.storageclass.storage.k8s.io/persistentvolumeclaims': {}
            'f:ibmc-vpcblock-odf-ret-custom.storageclass.storage.k8s.io/persistentvolumeclaims': {}
            'f:ibmc-vpc-block-metro-retain-custom.storageclass.storage.k8s.io/persistentvolumeclaims': {}
            'f:persistentvolumeclaims': {}
            'f:ibmc-vpcblock-odf-ret-5iops.storageclass.storage.k8s.io/persistentvolumeclaims': {}
            'f:ibmc-vpc-block-metro-retain-5iops-tier.storageclass.storage.k8s.io/persistentvolumeclaims': {}
            'f:ibmc-vpc-block-metro-general-purpose.storageclass.storage.k8s.io/persistentvolumeclaims': {}
    - manager: kube-controller-manager
      operation: Update
      apiVersion: v1
      time: '2023-01-04T13:45:08Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:status':
          'f:hard':
            'f:ibmc-vpc-block-metro-retain-general-purpose.storageclass.storage.k8s.io/persistentvolumeclaims': {}
            'f:ibmc-vpc-block-metro-custom.storageclass.storage.k8s.io/persistentvolumeclaims': {}
            'f:ibmc-vpc-block-metro-5iops-tier.storageclass.storage.k8s.io/persistentvolumeclaims': {}
            'f:pods': {}
            'f:limits.memory': {}
            'f:ibmc-vpcblock-odf-ret-10iops.storageclass.storage.k8s.io/persistentvolumeclaims': {}
            'f:ibmc-vpc-block-retain-10iops-tier.storageclass.storage.k8s.io/persistentvolumeclaims': {}
            'f:limits.cpu': {}
            'f:ibmc-vpcblock-odf-general.storageclass.storage.k8s.io/persistentvolumeclaims': {}
            'f:ibmc-vpcblock-odf-custom.storageclass.storage.k8s.io/persistentvolumeclaims': {}
            'f:ibmc-vpc-block-retain-custom.storageclass.storage.k8s.io/persistentvolumeclaims': {}
            'f:ibmc-vpc-block-general-purpose.storageclass.storage.k8s.io/persistentvolumeclaims': {}
            'f:ibmc-vpc-block-retain-5iops-tier.storageclass.storage.k8s.io/persistentvolumeclaims': {}
            'f:limits.ephemeral-storage': {}
            .: {}
            'f:ibmc-vpc-block-metro-10iops-tier.storageclass.storage.k8s.io/persistentvolumeclaims': {}
            'f:ibmc-vpcblock-odf-5iops.storageclass.storage.k8s.io/persistentvolumeclaims': {}
            'f:ibmc-vpcblock-odf-10iops.storageclass.storage.k8s.io/persistentvolumeclaims': {}
            'f:ibmc-vpc-block-metro-retain-10iops-tier.storageclass.storage.k8s.io/persistentvolumeclaims': {}
            'f:ibmc-vpcblock-odf-ret-general.storageclass.storage.k8s.io/persistentvolumeclaims': {}
            'f:requests.cpu': {}
            'f:ibmc-vpc-block-retain-general-purpose.storageclass.storage.k8s.io/persistentvolumeclaims': {}
            'f:ibmc-vpc-block-5iops-tier.storageclass.storage.k8s.io/persistentvolumeclaims': {}
            'f:ibmc-vpc-block-custom.storageclass.storage.k8s.io/persistentvolumeclaims': {}
            'f:requests.ephemeral-storage': {}
            'f:requests.memory': {}
            'f:skills-network-learner.storageclass.storage.k8s.io/persistentvolumeclaims': {}
            'f:ibmc-vpc-block-10iops-tier.storageclass.storage.k8s.io/persistentvolumeclaims': {}
            'f:ibmc-vpcblock-odf-ret-custom.storageclass.storage.k8s.io/persistentvolumeclaims': {}
            'f:ibmc-vpc-block-metro-retain-custom.storageclass.storage.k8s.io/persistentvolumeclaims': {}
            'f:persistentvolumeclaims': {}
            'f:ibmc-vpcblock-odf-ret-5iops.storageclass.storage.k8s.io/persistentvolumeclaims': {}
            'f:ibmc-vpc-block-metro-retain-5iops-tier.storageclass.storage.k8s.io/persistentvolumeclaims': {}
            'f:ibmc-vpc-block-metro-general-purpose.storageclass.storage.k8s.io/persistentvolumeclaims': {}
          'f:used':
            'f:ibmc-vpc-block-metro-retain-general-purpose.storageclass.storage.k8s.io/persistentvolumeclaims': {}
            'f:ibmc-vpc-block-metro-custom.storageclass.storage.k8s.io/persistentvolumeclaims': {}
            'f:ibmc-vpc-block-metro-5iops-tier.storageclass.storage.k8s.io/persistentvolumeclaims': {}
            'f:pods': {}
            'f:limits.memory': {}
            'f:ibmc-vpcblock-odf-ret-10iops.storageclass.storage.k8s.io/persistentvolumeclaims': {}
            'f:ibmc-vpc-block-retain-10iops-tier.storageclass.storage.k8s.io/persistentvolumeclaims': {}
            'f:limits.cpu': {}
            'f:ibmc-vpcblock-odf-general.storageclass.storage.k8s.io/persistentvolumeclaims': {}
            'f:ibmc-vpcblock-odf-custom.storageclass.storage.k8s.io/persistentvolumeclaims': {}
            'f:ibmc-vpc-block-retain-custom.storageclass.storage.k8s.io/persistentvolumeclaims': {}
            'f:ibmc-vpc-block-general-purpose.storageclass.storage.k8s.io/persistentvolumeclaims': {}
            'f:ibmc-vpc-block-retain-5iops-tier.storageclass.storage.k8s.io/persistentvolumeclaims': {}
            'f:limits.ephemeral-storage': {}
            .: {}
            'f:ibmc-vpc-block-metro-10iops-tier.storageclass.storage.k8s.io/persistentvolumeclaims': {}
            'f:ibmc-vpcblock-odf-5iops.storageclass.storage.k8s.io/persistentvolumeclaims': {}
            'f:ibmc-vpcblock-odf-10iops.storageclass.storage.k8s.io/persistentvolumeclaims': {}
            'f:ibmc-vpc-block-metro-retain-10iops-tier.storageclass.storage.k8s.io/persistentvolumeclaims': {}
            'f:ibmc-vpcblock-odf-ret-general.storageclass.storage.k8s.io/persistentvolumeclaims': {}
            'f:requests.cpu': {}
            'f:ibmc-vpc-block-retain-general-purpose.storageclass.storage.k8s.io/persistentvolumeclaims': {}
            'f:ibmc-vpc-block-5iops-tier.storageclass.storage.k8s.io/persistentvolumeclaims': {}
            'f:ibmc-vpc-block-custom.storageclass.storage.k8s.io/persistentvolumeclaims': {}
            'f:requests.ephemeral-storage': {}
            'f:requests.memory': {}
            'f:skills-network-learner.storageclass.storage.k8s.io/persistentvolumeclaims': {}
            'f:ibmc-vpc-block-10iops-tier.storageclass.storage.k8s.io/persistentvolumeclaims': {}
            'f:ibmc-vpcblock-odf-ret-custom.storageclass.storage.k8s.io/persistentvolumeclaims': {}
            'f:ibmc-vpc-block-metro-retain-custom.storageclass.storage.k8s.io/persistentvolumeclaims': {}
            'f:persistentvolumeclaims': {}
            'f:ibmc-vpcblock-odf-ret-5iops.storageclass.storage.k8s.io/persistentvolumeclaims': {}
            'f:ibmc-vpc-block-metro-retain-5iops-tier.storageclass.storage.k8s.io/persistentvolumeclaims': {}
            'f:ibmc-vpc-block-metro-general-purpose.storageclass.storage.k8s.io/persistentvolumeclaims': {}
      subresource: status
spec:
  hard:
    ibmc-vpc-block-5iops-tier.storageclass.storage.k8s.io/persistentvolumeclaims: '0'
    ibmc-vpc-block-retain-general-purpose.storageclass.storage.k8s.io/persistentvolumeclaims: '0'
    ibmc-vpc-block-custom.storageclass.storage.k8s.io/persistentvolumeclaims: '0'
    requests.ephemeral-storage: 50Gi
    ibmc-vpc-block-metro-10iops-tier.storageclass.storage.k8s.io/persistentvolumeclaims: '0'
    ibmc-vpcblock-odf-10iops.storageclass.storage.k8s.io/persistentvolumeclaims: '0'
    ibmc-vpcblock-odf-ret-5iops.storageclass.storage.k8s.io/persistentvolumeclaims: '0'
    persistentvolumeclaims: '6'
    requests.memory: 3Gi
    ibmc-vpc-block-metro-5iops-tier.storageclass.storage.k8s.io/persistentvolumeclaims: '0'
    ibmc-vpc-block-metro-custom.storageclass.storage.k8s.io/persistentvolumeclaims: '0'
    skills-network-learner.storageclass.storage.k8s.io/persistentvolumeclaims: '6'
    ibmc-vpc-block-metro-retain-general-purpose.storageclass.storage.k8s.io/persistentvolumeclaims: '0'
    ibmc-vpc-block-10iops-tier.storageclass.storage.k8s.io/persistentvolumeclaims: '0'
    pods: '50'
    ibmc-vpcblock-odf-ret-custom.storageclass.storage.k8s.io/persistentvolumeclaims: '0'
    ibmc-vpc-block-metro-retain-custom.storageclass.storage.k8s.io/persistentvolumeclaims: '0'
    ibmc-vpc-block-metro-retain-5iops-tier.storageclass.storage.k8s.io/persistentvolumeclaims: '0'
    ibmc-vpc-block-metro-general-purpose.storageclass.storage.k8s.io/persistentvolumeclaims: '0'
    ibmc-vpcblock-odf-general.storageclass.storage.k8s.io/persistentvolumeclaims: '0'
    limits.cpu: '4'
    ibmc-vpc-block-retain-10iops-tier.storageclass.storage.k8s.io/persistentvolumeclaims: '0'
    limits.ephemeral-storage: 75Gi
    limits.memory: 5Gi
    ibmc-vpcblock-odf-ret-10iops.storageclass.storage.k8s.io/persistentvolumeclaims: '0'
    ibmc-vpcblock-odf-custom.storageclass.storage.k8s.io/persistentvolumeclaims: '0'
    ibmc-vpcblock-odf-5iops.storageclass.storage.k8s.io/persistentvolumeclaims: '0'
    ibmc-vpc-block-general-purpose.storageclass.storage.k8s.io/persistentvolumeclaims: '0'
    ibmc-vpc-block-retain-5iops-tier.storageclass.storage.k8s.io/persistentvolumeclaims: '0'
    ibmc-vpc-block-retain-custom.storageclass.storage.k8s.io/persistentvolumeclaims: '0'
    requests.cpu: '2'
    ibmc-vpcblock-odf-ret-general.storageclass.storage.k8s.io/persistentvolumeclaims: '0'
    ibmc-vpc-block-metro-retain-10iops-tier.storageclass.storage.k8s.io/persistentvolumeclaims: '0'
status:
  hard:
    ibmc-vpc-block-5iops-tier.storageclass.storage.k8s.io/persistentvolumeclaims: '0'
    ibmc-vpc-block-retain-general-purpose.storageclass.storage.k8s.io/persistentvolumeclaims: '0'
    ibmc-vpc-block-custom.storageclass.storage.k8s.io/persistentvolumeclaims: '0'
    requests.ephemeral-storage: 50Gi
    ibmc-vpc-block-metro-10iops-tier.storageclass.storage.k8s.io/persistentvolumeclaims: '0'
    ibmc-vpcblock-odf-10iops.storageclass.storage.k8s.io/persistentvolumeclaims: '0'
    ibmc-vpcblock-odf-ret-5iops.storageclass.storage.k8s.io/persistentvolumeclaims: '0'
    persistentvolumeclaims: '6'
    requests.memory: 3Gi
    ibmc-vpc-block-metro-5iops-tier.storageclass.storage.k8s.io/persistentvolumeclaims: '0'
    ibmc-vpc-block-metro-custom.storageclass.storage.k8s.io/persistentvolumeclaims: '0'
    skills-network-learner.storageclass.storage.k8s.io/persistentvolumeclaims: '6'
    ibmc-vpc-block-metro-retain-general-purpose.storageclass.storage.k8s.io/persistentvolumeclaims: '0'
    ibmc-vpc-block-10iops-tier.storageclass.storage.k8s.io/persistentvolumeclaims: '0'
    pods: '50'
    ibmc-vpcblock-odf-ret-custom.storageclass.storage.k8s.io/persistentvolumeclaims: '0'
    ibmc-vpc-block-metro-retain-custom.storageclass.storage.k8s.io/persistentvolumeclaims: '0'
    ibmc-vpc-block-metro-retain-5iops-tier.storageclass.storage.k8s.io/persistentvolumeclaims: '0'
    ibmc-vpc-block-metro-general-purpose.storageclass.storage.k8s.io/persistentvolumeclaims: '0'
    ibmc-vpcblock-odf-general.storageclass.storage.k8s.io/persistentvolumeclaims: '0'
    limits.cpu: '4'
    ibmc-vpc-block-retain-10iops-tier.storageclass.storage.k8s.io/persistentvolumeclaims: '0'
    limits.ephemeral-storage: 75Gi
    limits.memory: 5Gi
    ibmc-vpcblock-odf-ret-10iops.storageclass.storage.k8s.io/persistentvolumeclaims: '0'
    ibmc-vpcblock-odf-custom.storageclass.storage.k8s.io/persistentvolumeclaims: '0'
    ibmc-vpcblock-odf-5iops.storageclass.storage.k8s.io/persistentvolumeclaims: '0'
    ibmc-vpc-block-general-purpose.storageclass.storage.k8s.io/persistentvolumeclaims: '0'
    ibmc-vpc-block-retain-5iops-tier.storageclass.storage.k8s.io/persistentvolumeclaims: '0'
    ibmc-vpc-block-retain-custom.storageclass.storage.k8s.io/persistentvolumeclaims: '0'
    requests.cpu: '2'
    ibmc-vpcblock-odf-ret-general.storageclass.storage.k8s.io/persistentvolumeclaims: '0'
    ibmc-vpc-block-metro-retain-10iops-tier.storageclass.storage.k8s.io/persistentvolumeclaims: '0'
  used:
    ibmc-vpc-block-5iops-tier.storageclass.storage.k8s.io/persistentvolumeclaims: '0'
    ibmc-vpc-block-retain-general-purpose.storageclass.storage.k8s.io/persistentvolumeclaims: '0'
    ibmc-vpc-block-custom.storageclass.storage.k8s.io/persistentvolumeclaims: '0'
    requests.ephemeral-storage: 2560Mi
    ibmc-vpc-block-metro-10iops-tier.storageclass.storage.k8s.io/persistentvolumeclaims: '0'
    ibmc-vpcblock-odf-10iops.storageclass.storage.k8s.io/persistentvolumeclaims: '0'
    ibmc-vpcblock-odf-ret-5iops.storageclass.storage.k8s.io/persistentvolumeclaims: '0'
    persistentvolumeclaims: '0'
    requests.memory: 440Mi
    ibmc-vpc-block-metro-5iops-tier.storageclass.storage.k8s.io/persistentvolumeclaims: '0'
    ibmc-vpc-block-metro-custom.storageclass.storage.k8s.io/persistentvolumeclaims: '0'
    skills-network-learner.storageclass.storage.k8s.io/persistentvolumeclaims: '0'
    ibmc-vpc-block-metro-retain-general-purpose.storageclass.storage.k8s.io/persistentvolumeclaims: '0'
    ibmc-vpc-block-10iops-tier.storageclass.storage.k8s.io/persistentvolumeclaims: '0'
    pods: '3'
    ibmc-vpcblock-odf-ret-custom.storageclass.storage.k8s.io/persistentvolumeclaims: '0'
    ibmc-vpc-block-metro-retain-custom.storageclass.storage.k8s.io/persistentvolumeclaims: '0'
    ibmc-vpc-block-metro-retain-5iops-tier.storageclass.storage.k8s.io/persistentvolumeclaims: '0'
    ibmc-vpc-block-metro-general-purpose.storageclass.storage.k8s.io/persistentvolumeclaims: '0'
    ibmc-vpcblock-odf-general.storageclass.storage.k8s.io/persistentvolumeclaims: '0'
    limits.cpu: 230m
    ibmc-vpc-block-retain-10iops-tier.storageclass.storage.k8s.io/persistentvolumeclaims: '0'
    limits.ephemeral-storage: 9Gi
    limits.memory: 1124Mi
    ibmc-vpcblock-odf-ret-10iops.storageclass.storage.k8s.io/persistentvolumeclaims: '0'
    ibmc-vpcblock-odf-custom.storageclass.storage.k8s.io/persistentvolumeclaims: '0'
    ibmc-vpcblock-odf-5iops.storageclass.storage.k8s.io/persistentvolumeclaims: '0'
    ibmc-vpc-block-general-purpose.storageclass.storage.k8s.io/persistentvolumeclaims: '0'
    ibmc-vpc-block-retain-5iops-tier.storageclass.storage.k8s.io/persistentvolumeclaims: '0'
    ibmc-vpc-block-retain-custom.storageclass.storage.k8s.io/persistentvolumeclaims: '0'
    requests.cpu: 43m
    ibmc-vpcblock-odf-ret-general.storageclass.storage.k8s.io/persistentvolumeclaims: '0'
    ibmc-vpc-block-metro-retain-10iops-tier.storageclass.storage.k8s.io/persistentvolumeclaims: '0'
