kind: ReplicaSet
apiVersion: apps/v1
metadata:
  annotations:
    alpha.image.policy.openshift.io/resolve-names: '*'
    app.openshift.io/vcs-ref: ''
    app.openshift.io/vcs-uri: >-
      https://github.com/husseinahmed-dev/Research-Project-1-Kubernetes-Hardening.git
    deployment.kubernetes.io/desired-replicas: '1'
    deployment.kubernetes.io/max-replicas: '2'
    deployment.kubernetes.io/revision: '1'
    image.openshift.io/triggers: >-
      [{"from":{"kind":"ImageStreamTag","name":"rp1-5app-nodejs:latest","namespace":"sn-labs-husseinashah"},"fieldPath":"spec.template.spec.containers[?(@.name==\"rp1-5app-nodejs\")].image","pause":"false"}]
    openshift.io/generated-by: OpenShiftWebConsole
  resourceVersion: '810068978'
  name: rp1-5app-nodejs-794c8f4788
  uid: b47d3050-72ad-438a-8c26-db6f3b7ad69c
  creationTimestamp: '2023-01-04T13:19:55Z'
  generation: 2
  managedFields:
    - manager: kube-controller-manager
      operation: Update
      apiVersion: apps/v1
      time: '2023-01-04T13:19:55Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:metadata':
          'f:annotations':
            'f:deployment.kubernetes.io/desired-replicas': {}
            'f:image.openshift.io/triggers': {}
            .: {}
            'f:deployment.kubernetes.io/revision': {}
            'f:app.openshift.io/vcs-uri': {}
            'f:openshift.io/generated-by': {}
            'f:alpha.image.policy.openshift.io/resolve-names': {}
            'f:deployment.kubernetes.io/max-replicas': {}
            'f:app.openshift.io/vcs-ref': {}
          'f:labels':
            .: {}
            'f:app': {}
            'f:deploymentconfig': {}
            'f:pod-template-hash': {}
          'f:ownerReferences':
            .: {}
            'k:{"uid":"4e622c89-380b-4bec-bc9f-de825eeba431"}': {}
        'f:spec':
          'f:replicas': {}
          'f:selector': {}
          'f:template':
            'f:metadata':
              'f:labels':
                .: {}
                'f:app': {}
                'f:deploymentconfig': {}
                'f:pod-template-hash': {}
            'f:spec':
              'f:containers':
                'k:{"name":"rp1-5app-nodejs"}':
                  .: {}
                  'f:image': {}
                  'f:imagePullPolicy': {}
                  'f:name': {}
                  'f:ports':
                    .: {}
                    'k:{"containerPort":8080,"protocol":"TCP"}':
                      .: {}
                      'f:containerPort': {}
                      'f:protocol': {}
                  'f:resources': {}
                  'f:terminationMessagePath': {}
                  'f:terminationMessagePolicy': {}
              'f:dnsPolicy': {}
              'f:restartPolicy': {}
              'f:schedulerName': {}
              'f:securityContext': {}
              'f:terminationGracePeriodSeconds': {}
    - manager: kube-controller-manager
      operation: Update
      apiVersion: apps/v1
      time: '2023-01-04T13:22:18Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:status':
          'f:observedGeneration': {}
          'f:replicas': {}
      subresource: status
  namespace: sn-labs-husseinashah
  ownerReferences:
    - apiVersion: apps/v1
      kind: Deployment
      name: rp1-5app-nodejs
      uid: 4e622c89-380b-4bec-bc9f-de825eeba431
      controller: true
      blockOwnerDeletion: true
  labels:
    app: rp1-5app-nodejs
    deploymentconfig: rp1-5app-nodejs
    pod-template-hash: 794c8f4788
spec:
  replicas: 0
  selector:
    matchLabels:
      app: rp1-5app-nodejs
      pod-template-hash: 794c8f4788
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: rp1-5app-nodejs
        deploymentconfig: rp1-5app-nodejs
        pod-template-hash: 794c8f4788
    spec:
      containers:
        - name: rp1-5app-nodejs
          image: >-
            image-registry.openshift-image-registry.svc:5000/sn-labs-husseinashah/rp1-5app-nodejs:latest
          ports:
            - containerPort: 8080
              protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: Always
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
status:
  replicas: 0
  observedGeneration: 2
