kind: ReplicaSet
apiVersion: apps/v1
metadata:
  annotations:
    deployment.kubernetes.io/desired-replicas: '1'
    deployment.kubernetes.io/max-replicas: '2'
    deployment.kubernetes.io/revision: '1'
  resourceVersion: '810326959'
  name: guestbook-5bbf8cd45f
  uid: 7022c965-3033-4f7a-9428-2ad9a7899eaa
  creationTimestamp: '2023-01-04T18:52:14Z'
  generation: 5
  managedFields:
    - manager: kube-controller-manager
      operation: Update
      apiVersion: apps/v1
      time: '2023-01-04T18:52:14Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:metadata':
          'f:annotations':
            .: {}
            'f:deployment.kubernetes.io/desired-replicas': {}
            'f:deployment.kubernetes.io/max-replicas': {}
            'f:deployment.kubernetes.io/revision': {}
          'f:labels':
            .: {}
            'f:app': {}
            'f:pod-template-hash': {}
          'f:ownerReferences':
            .: {}
            'k:{"uid":"7ecd782b-ad58-45ea-b5a6-412f14d3b45f"}': {}
        'f:spec':
          'f:replicas': {}
          'f:selector': {}
          'f:template':
            'f:metadata':
              'f:labels':
                .: {}
                'f:app': {}
                'f:pod-template-hash': {}
            'f:spec':
              'f:containers':
                'k:{"name":"guestbook"}':
                  .: {}
                  'f:image': {}
                  'f:imagePullPolicy': {}
                  'f:name': {}
                  'f:ports':
                    .: {}
                    'k:{"containerPort":3000,"protocol":"TCP"}':
                      .: {}
                      'f:containerPort': {}
                      'f:name': {}
                      'f:protocol': {}
                  'f:resources':
                    .: {}
                    'f:limits':
                      .: {}
                      'f:cpu': {}
                    'f:requests':
                      .: {}
                      'f:cpu': {}
                  'f:terminationMessagePath': {}
                  'f:terminationMessagePolicy': {}
              'f:dnsPolicy': {}
              'f:restartPolicy': {}
              'f:schedulerName': {}
              'f:securityContext': {}
              'f:terminationGracePeriodSeconds': {}
    - manager: kube-controller-manager
      operation: Update
      apiVersion: apps/v1
      time: '2023-01-04T19:08:51Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:status':
          'f:observedGeneration': {}
          'f:replicas': {}
      subresource: status
  namespace: sn-labs-husseinashah
  ownerReferences:
    - apiVersion: apps/v1
      kind: Deployment
      name: guestbook
      uid: 7ecd782b-ad58-45ea-b5a6-412f14d3b45f
      controller: true
      blockOwnerDeletion: true
  labels:
    app: guestbook
    pod-template-hash: 5bbf8cd45f
spec:
  replicas: 0
  selector:
    matchLabels:
      app: guestbook
      pod-template-hash: 5bbf8cd45f
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: guestbook
        pod-template-hash: 5bbf8cd45f
    spec:
      containers:
        - name: guestbook
          image: 'us.icr.io/sn-labs-husseinashah/guestbook:v1'
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
          resources:
            limits:
              cpu: 50m
            requests:
              cpu: 20m
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: Always
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
status:
  replicas: 0
  observedGeneration: 5
