kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: openshift-pipelines-edit
  namespace: sn-labs-husseinashah
  uid: e3f49aff-0626-4770-bc74-98d7ca9c5882
  resourceVersion: '809977807'
  creationTimestamp: '2023-01-04T11:20:52Z'
  ownerReferences:
    - apiVersion: operator.tekton.dev/v1alpha1
      kind: TektonInstallerSet
      name: rhosp-rbac-zfwgf
      uid: 6964b787-84d8-4878-978e-6e0f4f6ff99e
      controller: true
      blockOwnerDeletion: true
  managedFields:
    - manager: openshift-pipelines-operator
      operation: Update
      apiVersion: rbac.authorization.k8s.io/v1
      time: '2023-01-04T11:20:52Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:metadata':
          'f:ownerReferences':
            .: {}
            'k:{"uid":"6964b787-84d8-4878-978e-6e0f4f6ff99e"}': {}
        'f:roleRef': {}
        'f:subjects': {}
subjects:
  - kind: ServiceAccount
    name: pipeline
    namespace: sn-labs-husseinashah
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: edit
